apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-eval

secretGenerator:
    - name: llm-eval-app-config
      envs:
          - .env.secret
generatorOptions:
  disableNameSuffixHash: true

resources:
    - deployment.yaml
    - service.yaml
    - route.yaml

