apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-eval

secretGenerator:
    - name: aws-connection-aws-s3
      envs:
          - .env.secret
generatorOptions:
    disableNameSuffixHash: true

resources:
    - ../../base

patches:
    - path: patch-deployment.yaml