apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: llm-eval

resources:
    - ../../base
    - sa.yaml
    - rolebinding.yaml
    - service.yaml
    - pvc.yaml
    - deployment.yaml
    - job_create_ds_connections.yaml
    - job_create_bucket.yaml
    - job_create_minio_root_user.yaml
    - route_console.yaml
    - route_s3.yaml

patches:
    - path: patch-deployment.yaml